const fs = require('fs');

// Fix 1: app/api/webhooks/paystack/route.ts
const webhook = [
'import { NextRequest, NextResponse } from "next/server";',
'import { supabaseAdmin } from "@/lib/supabase";',
'import { verifyWebhookSignature } from "@/lib/paystack";',
'import { sendReceiptEmail } from "@/lib/email";',
'import { generateReceiptNumber, koboToNaira } from "@/lib/utils";',
'',
'export async function POST(req: NextRequest) {',
'  const rawBody = await req.text();',
'  const signature = req.headers.get("x-paystack-signature") ?? "";',
'',
'  if (!verifyWebhookSignature(rawBody, signature)) {',
'    return NextResponse.json({ error: "Invalid signature" }, { status: 401 });',
'  }',
'',
'  const event = JSON.parse(rawBody);',
'  console.log("Webhook event:", event.event, "channel:", event.data?.channel);',
'',
'  if (event.event === "charge.success") {',
'    const { reference, amount, channel, paid_at, metadata } = event.data;',
'',
'    const invoiceId: string = metadata?.invoice_id;',
'    if (invoiceId) {',
'      await handleInvoicePaid({ invoiceId, reference, amount, channel, paid_at });',
'      return NextResponse.json({ ok: true });',
'    }',
'',
'    if (channel === "dedicated_nuban" || channel === "bank_transfer") {',
'      const receiverAccount =',
'        event.data?.authorization?.receiver_bank_account_number ??',
'        event.data?.metadata?.receiver_account_number ??',
'        null;',
'',
'      const amountNaira = koboToNaira(amount);',
'      console.log("DVA payment — receiver:", receiverAccount, "amount (naira):", amountNaira);',
'',
'      if (!receiverAccount) {',
'        console.log("Could not determine receiver account");',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      const { data: business } = await supabaseAdmin',
'        .from("businesses")',
'        .select("user_id")',
'        .eq("dva_account_number", receiverAccount)',
'        .single();',
'',
'      if (!business) {',
'        console.log("No business found with DVA account:", receiverAccount);',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      const { data: invoices } = await supabaseAdmin',
'        .from("invoices")',
'        .select("*")',
'        .eq("user_id", business.user_id)',
'        .eq("status", "sent")',
'        .order("created_at", { ascending: false });',
'',
'      if (!invoices || invoices.length === 0) {',
'        console.log("No unpaid invoices for business");',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      console.log("Unpaid invoices:", invoices.map((i: any) => ({ id: i.id, total: i.total })));',
'',
'      const matched = invoices.find((inv: any) => Math.abs(Number(inv.total) - amountNaira) < 1);',
'',
'      if (!matched) {',
'        console.log("No invoice matched amount:", amountNaira);',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      await handleInvoicePaid({ invoiceId: matched.id, reference, amount, channel, paid_at });',
'    }',
'  }',
'',
'  return NextResponse.json({ ok: true });',
'}',
'',
'async function handleInvoicePaid({',
'  invoiceId,',
'  reference,',
'  amount,',
'  channel,',
'  paid_at,',
'}: {',
'  invoiceId: string;',
'  reference: string;',
'  amount: number;',
'  channel: string;',
'  paid_at: string;',
'}) {',
'  const { data: invoice } = await supabaseAdmin',
'    .from("invoices")',
'    .select("*")',
'    .eq("id", invoiceId)',
'    .single();',
'',
'  if (!invoice || invoice.status === "paid") return;',
'',
'  await supabaseAdmin',
'    .from("invoices")',
'    .update({ status: "paid", paid_at })',
'    .eq("id", invoiceId);',
'',
'  const receiptNumber = generateReceiptNumber(invoice.invoice_number);',
'  const { data: receipt } = await supabaseAdmin',
'    .from("receipts")',
'    .insert({',
'      invoice_id: invoiceId,',
'      user_id: invoice.user_id,',
'      receipt_number: receiptNumber,',
'      amount_paid: invoice.currency === "NGN" ? koboToNaira(amount) : amount / 100,',
'      payment_method: channel,',
'      paystack_reference: reference,',
'      paid_at,',
'    })',
'    .select()',
'    .single();',
'',
'  const { data: business } = await supabaseAdmin',
'    .from("businesses")',
'    .select("*")',
'    .eq("user_id", invoice.user_id)',
'    .single();',
'',
'  if (invoice.client_email && receipt) {',
'    await sendReceiptEmail(invoice, receipt, business).catch(console.error);',
'    await supabaseAdmin',
'      .from("receipts")',
'      .update({ emailed_at: new Date().toISOString() })',
'      .eq("id", receipt.id);',
'  }',
'',
'  console.log("Invoice marked paid:", invoiceId);',
'}',
'',
'export const config = { api: { bodyParser: false } };',
].join('\n');

fs.writeFileSync('app/api/webhooks/paystack/route.ts', webhook, { encoding: 'utf8' });
console.log('Fixed webhook');

// Fix 2: app/invoices/new/page.tsx
const newInvoice = [
'"use client";',
'import { useState, useEffect } from "react";',
'import { supabase } from "@/lib/supabase";',
'import { useRouter } from "next/navigation";',
'import { calcTotals, formatCurrency } from "@/lib/utils";',
'',
'interface LineItem { id: number; description: string; qty: number; unit_price: string; }',
'',
'const CURRENCIES = ["NGN", "USD", "GBP", "EUR"];',
'const emptyItem = (): LineItem => ({ id: Date.now(), description: "", qty: 1, unit_price: "" });',
'',
'export default function NewInvoice() {',
'  const router = useRouter();',
'  const [userId, setUserId] = useState<string | null>(null);',
'  const [saving, setSaving] = useState(false);',
'  const [currency, setCurrency] = useState("NGN");',
'  const [items, setItems] = useState<LineItem[]>([emptyItem()]);',
'  const [client, setClient] = useState({ name: "", email: "", phone: "", address: "" });',
'  const [discountType, setDiscountType] = useState<"percent" | "flat">("percent");',
'  const [discountValue, setDiscountValue] = useState(0);',
'  const [taxRate, setTaxRate] = useState(7.5);',
'  const [notes, setNotes] = useState("");',
'  const [paymentInfo, setPaymentInfo] = useState("");',
'  const [issueDate, setIssueDate] = useState(new Date().toISOString().split("T")[0]);',
'  const [dueDate, setDueDate] = useState("");',
'  const [showDuplicateModal, setShowDuplicateModal] = useState(false);',
'  const [duplicateInvoice, setDuplicateInvoice] = useState<{ invoice_number: string; status: string } | null>(null);',
'  const [pendingSendNow, setPendingSendNow] = useState(false);',
'',
'  useEffect(() => {',
'    supabase.auth.getUser().then(({ data }) => {',
'      if (!data.user) { router.push("/"); return; }',
'      setUserId(data.user.id);',
'    });',
'  }, [router]);',
'',
'  const parsedItems = items.map(i => ({ description: i.description, qty: Number(i.qty), unit_price: Number(i.unit_price) || 0 }));',
'  const { subtotal, discountAmount, taxAmount, total } = calcTotals(parsedItems, discountType, discountValue, taxRate);',
'',
'  const updateItem = (id: number, field: keyof LineItem, val: string | number) =>',
'    setItems(items.map(i => i.id === id ? { ...i, [field]: val } : i));',
'',
'  const doSave = async (sendNow: boolean) => {',
'    if (!userId || !client.name.trim()) return;',
'    setSaving(true);',
'    const res = await fetch("/api/invoices", {',
'      method: "POST",',
'      headers: { "Content-Type": "application/json" },',
'      body: JSON.stringify({',
'        user_id: userId,',
'        client_name: client.name, client_email: client.email,',
'        client_phone: client.phone, client_address: client.address,',
'        items: parsedItems,',
'        discount_type: discountType, discount_value: discountValue,',
'        tax_rate: taxRate, notes, payment_info: paymentInfo,',
'        issue_date: issueDate, due_date: dueDate, currency,',
'      }),',
'    });',
'    const data = await res.json();',
'    setSaving(false);',
'    if (data.invoice) {',
'      if (sendNow && client.email) {',
'        await fetch(`/api/invoices/${data.invoice.id}/payment-link`, { method: "POST" });',
'      }',
'      router.push(`/invoices/${data.invoice.id}`);',
'    }',
'  };',
'',
'  const handleSave = async (sendNow: boolean) => {',
'    if (!userId || !client.name.trim()) return;',
'    const { data: existing } = await supabase',
'      .from("invoices")',
'      .select("id, invoice_number, status")',
'      .eq("user_id", userId)',
'      .eq("client_name", client.name.trim())',
'      .eq("total", total)',
'      .neq("status", "cancelled")',
'      .order("created_at", { ascending: false })',
'      .limit(1);',
'    if (existing && existing.length > 0) {',
'      setDuplicateInvoice(existing[0]);',
'      setPendingSendNow(sendNow);',
'      setShowDuplicateModal(true);',
'      return;',
'    }',
'    await doSave(sendNow);',
'  };',
'',
'  const handleConfirmDuplicate = async () => {',
'    setShowDuplicateModal(false);',
'    setDuplicateInvoice(null);',
'    await doSave(pendingSendNow);',
'  };',
'',
'  const handleCancelDuplicate = () => {',
'    setShowDuplicateModal(false);',
'    setDuplicateInvoice(null);',
'  };',
'',
'  const inputStyle = { width: "100%", padding: "9px 12px", border: "1.5px solid var(--border)", borderRadius: 7, fontSize: 14, outline: "none", fontFamily: "var(--font-body)" };',
'  const labelStyle = { display: "block" as const, fontSize: 11, fontWeight: 700 as const, textTransform: "uppercase" as const, letterSpacing: "0.8px", color: "var(--muted)", marginBottom: 5 };',
'',
'  return (',
'    <div style={{ minHeight: "100vh", background: "var(--cream)" }}>',
'',
'      {showDuplicateModal && duplicateInvoice && (',
'        <div style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.5)", zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center", padding: 24 }}>',
'          <div style={{ background: "white", borderRadius: 14, padding: 32, maxWidth: 440, width: "100%", boxShadow: "0 20px 60px rgba(0,0,0,0.2)" }}>',
'            <div style={{ fontSize: 36, textAlign: "center", marginBottom: 16 }}>&#x26A0;&#xFE0F;</div>',
'            <div style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 700, marginBottom: 8, textAlign: "center" }}>Possible Duplicate Invoice</div>',
'            <div style={{ fontSize: 14, color: "var(--muted)", textAlign: "center", marginBottom: 20, lineHeight: 1.6 }}>',
'              A similar invoice already exists for this client with the same amount.',
'            </div>',
'            <div style={{ background: "#fff8e8", border: "1px solid #f0d080", borderRadius: 10, padding: "14px 18px", marginBottom: 24 }}>',
'              <div style={{ fontSize: 13, color: "#7a5500", lineHeight: 1.9 }}>',
'                <span style={{ color: "#555" }}>Invoice: </span><strong>{duplicateInvoice.invoice_number}</strong><br />',
'                <span style={{ color: "#555" }}>Client: </span><strong>{client.name}</strong><br />',
'                <span style={{ color: "#555" }}>Amount: </span><strong>{formatCurrency(total, currency)}</strong><br />',
'                <span style={{ color: "#555" }}>Status: </span><strong style={{ textTransform: "uppercase" }}>{duplicateInvoice.status}</strong>',
'              </div>',
'            </div>',
'            <div style={{ display: "flex", gap: 12 }}>',
'              <button onClick={handleCancelDuplicate} style={{ flex: 1, padding: "11px", background: "#f5f2ed", color: "var(--text)", border: "1.5px solid var(--border)", borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "var(--font-body)" }}>',
'                Cancel',
'              </button>',
'              <button onClick={handleConfirmDuplicate} style={{ flex: 1, padding: "11px", background: "var(--green)", color: "white", border: "none", borderRadius: 8, fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "var(--font-body)" }}>',
'                Create Anyway',
'              </button>',
'            </div>',
'          </div>',
'        </div>',
'      )}',
'',
'      <nav style={{ background: "var(--green)", padding: "0 28px", height: 60, display: "flex", alignItems: "center", gap: 16 }}>',
'        <button onClick={() => router.push("/dashboard")} style={{ background: "none", border: "none", color: "white", cursor: "pointer", fontSize: 20, lineHeight: 1 }}>&#8592;</button>',
'        <div style={{ fontFamily: "var(--font-display)", fontSize: 20, fontWeight: 700, color: "white" }}>New Invoice</div>',
'      </nav>',
'',
'      <div style={{ maxWidth: 860, margin: "0 auto", padding: "28px 20px" }}>',
'',
'        <div style={{ background: "white", borderRadius: 12, border: "1px solid var(--border)", marginBottom: 16, overflow: "hidden" }}>',
'          <div style={{ padding: "12px 20px", background: "#faf9f7", borderBottom: "1px solid var(--border)", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, color: "var(--muted)" }}>Invoice Details</div>',
'          <div style={{ padding: 20, display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 14 }}>',
'            <div><label style={labelStyle}>Currency</label>',
'              <select value={currency} onChange={e => setCurrency(e.target.value)} style={inputStyle}>',
'                {CURRENCIES.map(c => <option key={c}>{c}</option>)}',
'              </select>',
'            </div>',
'            <div><label style={labelStyle}>Issue Date</label><input type="date" value={issueDate} onChange={e => setIssueDate(e.target.value)} style={inputStyle} /></div>',
'            <div><label style={labelStyle}>Due Date</label><input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} style={inputStyle} /></div>',
'          </div>',
'        </div>',
'',
'        <div style={{ background: "white", borderRadius: 12, border: "1px solid var(--border)", marginBottom: 16, overflow: "hidden" }}>',
'          <div style={{ padding: "12px 20px", background: "#faf9f7", borderBottom: "1px solid var(--border)", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, color: "var(--muted)" }}>Client Information</div>',
'          <div style={{ padding: 20, display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 14 }}>',
'            <div>',
'              <label style={labelStyle}>Client Name *</label>',
'              <input value={client.name} onChange={e => setClient({ ...client, name: e.target.value })} style={inputStyle} placeholder="Client or company name" required />',
'            </div>',
'            <div>',
'              <label style={{ ...labelStyle }}>Email <span style={{ fontWeight: 400, color: "#bbb", textTransform: "none" }}>(optional)</span></label>',
'              <input value={client.email} onChange={e => setClient({ ...client, email: e.target.value })} style={inputStyle} placeholder="client@email.com" />',
'            </div>',
'            <div>',
'              <label style={{ ...labelStyle }}>Phone <span style={{ fontWeight: 400, color: "#bbb", textTransform: "none" }}>(optional)</span></label>',
'              <input value={client.phone} onChange={e => setClient({ ...client, phone: e.target.value })} style={inputStyle} placeholder="+234..." />',
'            </div>',
'            <div>',
'              <label style={{ ...labelStyle }}>Address <span style={{ fontWeight: 400, color: "#bbb", textTransform: "none" }}>(optional)</span></label>',
'              <input value={client.address} onChange={e => setClient({ ...client, address: e.target.value })} style={inputStyle} />',
'            </div>',
'          </div>',
'        </div>',
'',
'        <div style={{ background: "white", borderRadius: 12, border: "1px solid var(--border)", marginBottom: 16, overflow: "hidden" }}>',
'          <div style={{ padding: "12px 20px", background: "#faf9f7", borderBottom: "1px solid var(--border)", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: 1, color: "var(--muted)" }}>Line Items</div>',
'          <div style={{ padding: 20, overflowX: "auto" }}>',
'            <table style={{ width: "100%", borderCollapse: "collapse" }}>',
'              <thead>',
'                <tr>{["Description", "Qty", "Unit Price", "Amount", ""].map(h => (',
'                  <th key={h} style={{ padding: "8px 8px", fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.8px", color: "var(--muted)", textAlign: h === "Amount" ? "right" : "left", borderBottom: "1.5px solid var(--border)" }}>{h}</th>',
'                ))}</tr>',
'              </thead>',
'              <tbody>',
'                {items.map(item => (',
'                  <tr key={item.id}>',
'                    <td style={{ padding: "7px 6px" }}><input value={item.description} onChange={e => updateItem(item.id, "description", e.target.value)} style={{ ...inputStyle, minWidth: 200 }} placeholder="Service / product" /></td>',
'                    <td style={{ padding: "7px 6px" }}><input type="number" min={0} value={item.qty} onChange={e => updateItem(item.id, "qty", e.target.value)} style={{ ...inputStyle, width: 70 }} /></td>',
'                    <td style={{ padding: "7px 6px" }}><input type="number" min={0} value={item.unit_price} onChange={e => updateItem(item.id, "unit_price", e.target.value)} style={{ ...inputStyle, width: 130 }} placeholder="0.00" /></td>',
'                    <td style={{ padding: "7px 6px", textAlign: "right", fontWeight: 600, fontSize: 14 }}>{formatCurrency(item.qty * (Number(item.unit_price) || 0), currency)}</td>',
'                    <td style={{ padding: "7px 6px" }}><button onClick={() => items.length > 1 && setItems(items.filter(i => i.id !== item.id))} style={{ background: "none", border: "none", cursor: "pointer", color: "#ccc", fontSize: 20, lineHeight: 1 }}>x</button></td>',
'                  </tr>',
'                ))}',
'              </tbody>',
'            </table>',
'            <button onClick={() => setItems([...items, emptyItem()])} style={{ marginTop: 12, padding: "8px 16px", border: "1.5px dashed var(--green-accent)", borderRadius: 7, background: "var(--green-light)", color: "var(--green)", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "var(--font-body)" }}>+ Add Item</button>',
'          </div>',
'          <div style={{ padding: "16px 20px", borderTop: "1px solid var(--border)", display: "flex", justifyContent: "space-between", flexWrap: "wrap", gap: 20 }}>',
'            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, flex: 1, minWidth: 280 }}>',
'              <div><label style={labelStyle}>Discount</label><input type="number" min={0} value={discountValue} onChange={e => setDiscountValue(Number(e.target.value))} style={inputStyle} /></div>',
'              <div><label style={labelStyle}>Discount Type</label><select value={discountType} onChange={e => setDiscountType(e.target.value as "percent" | "flat")} style={inputStyle}><option value="percent">%</option><option value="flat">Flat</option></select></div>',
'              <div><label style={labelStyle}>Tax Rate %</label><input type="number" min={0} max={100} value={taxRate} onChange={e => setTaxRate(Number(e.target.value))} style={inputStyle} /></div>',
'            </div>',
'            <div style={{ minWidth: 220 }}>',
'              {[',
'                ["Subtotal", formatCurrency(subtotal, currency)],',
'                discountAmount > 0 ? ["Discount", "-" + formatCurrency(discountAmount, currency)] : null,',
'                taxAmount > 0 ? ["Tax (" + taxRate + "%)", formatCurrency(taxAmount, currency)] : null,',
'              ].filter(Boolean).map(([label, val]) => (',
'                <div key={label as string} style={{ display: "flex", justifyContent: "space-between", fontSize: 13, color: "var(--muted)", padding: "4px 0" }}>',
'                  <span>{label}