const fs = require('fs');

const content = [
'import { NextRequest, NextResponse } from "next/server";',
'import { supabaseAdmin } from "@/lib/supabase";',
'import { verifyWebhookSignature } from "@/lib/paystack";',
'import { sendReceiptEmail } from "@/lib/email";',
'import { generateReceiptNumber, koboToNaira } from "@/lib/utils";',
'',
'const PAYSTACK_SECRET = process.env.PAYSTACK_SECRET_KEY!;',
'const BASE = "https://api.paystack.co";',
'',
'function paystackHeaders() {',
'  return {',
'    Authorization: `Bearer ${PAYSTACK_SECRET}`,',
'    "Content-Type": "application/json",',
'  };',
'}',
'',
'async function transferToBusiness(business: any, amountKobo: number) {',
'  try {',
'    if (!business.bank_code || !business.account_number) {',
'      console.log("Business has no payout account set up");',
'      return;',
'    }',
'',
'    // Platform takes 2%, business gets 98%',
'    const paystackFeeKobo = Math.round(amountKobo * 0.01); // Paystack DVA fee ~1%',
'    const businessShareKobo = Math.round((amountKobo - paystackFeeKobo) * 0.98);',
'',
'    console.log(`DVA payout: total=${amountKobo}, businessShare=${businessShareKobo}`);',
'',
'    // Step 1 - Create transfer recipient',
'    const recipientRes = await fetch(`${BASE}/transferrecipient`, {',
'      method: "POST",',
'      headers: paystackHeaders(),',
'      body: JSON.stringify({',
'        type: "nuban",',
'        name: business.account_name,',
'        account_number: business.account_number,',
'        bank_code: business.bank_code,',
'        currency: "NGN",',
'      }),',
'    });',
'    const recipientData = await recipientRes.json();',
'    if (!recipientData.status) {',
'      console.error("Failed to create transfer recipient:", recipientData.message);',
'      return;',
'    }',
'    const recipientCode = recipientData.data.recipient_code;',
'',
'    // Step 2 - Initiate transfer',
'    const transferRes = await fetch(`${BASE}/transfer`, {',
'      method: "POST",',
'      headers: paystackHeaders(),',
'      body: JSON.stringify({',
'        source: "balance",',
'        amount: businessShareKobo,',
'        recipient: recipientCode,',
'        reason: `BizDoc DVA payout - ${business.name}`,',
'      }),',
'    });',
'    const transferData = await transferRes.json();',
'    console.log("Transfer result:", transferData.status, transferData.message);',
'  } catch (err) {',
'    console.error("Transfer failed:", err);',
'  }',
'}',
'',
'export async function POST(req: NextRequest) {',
'  const rawBody = await req.text();',
'  const signature = req.headers.get("x-paystack-signature") ?? "";',
'',
'  if (!verifyWebhookSignature(rawBody, signature)) {',
'    return NextResponse.json({ error: "Invalid signature" }, { status: 401 });',
'  }',
'',
'  const event = JSON.parse(rawBody);',
'  console.log("Webhook event:", event.event, "channel:", event.data?.channel);',
'',
'  if (event.event === "charge.success") {',
'    const { reference, amount, channel, paid_at, metadata } = event.data;',
'',
'    // Standard Paystack checkout payment (has invoice_id in metadata)',
'    const invoiceId: string = metadata?.invoice_id;',
'    if (invoiceId) {',
'      await handleInvoicePaid({ invoiceId, reference, amount, channel, paid_at, isDva: false });',
'      return NextResponse.json({ ok: true });',
'    }',
'',
'    // DVA payment - match by receiver account number + exact amount',
'    if (channel === "dedicated_nuban" || channel === "bank_transfer") {',
'      const receiverAccount = event.data?.authorization?.receiver_bank_account_number',
'        ?? event.data?.metadata?.receiver_account_number',
'        ?? null;',
'',
'      const amountNaira = koboToNaira(amount);',
'      console.log("DVA payment - receiver:", receiverAccount, "amount (naira):", amountNaira);',
'',
'      if (!receiverAccount) {',
'        console.log("Could not determine receiver account");',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      const { data: business } = await supabaseAdmin',
'        .from("businesses")',
'        .select("*")',
'        .eq("dva_account_number", receiverAccount)',
'        .single();',
'',
'      if (!business) {',
'        console.log("No business found with DVA account:", receiverAccount);',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      const { data: invoices } = await supabaseAdmin',
'        .from("invoices")',
'        .select("*")',
'        .eq("user_id", business.user_id)',
'        .eq("status", "sent")',
'        .order("created_at", { ascending: false });',
'',
'      if (!invoices || invoices.length === 0) {',
'        console.log("No unpaid invoices for business");',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      const matched = invoices.find((inv: any) => Math.abs(Number(inv.total) - amountNaira) < 1);',
'',
'      if (!matched) {',
'        console.log("No invoice matched amount:", amountNaira);',
'        return NextResponse.json({ ok: true });',
'      }',
'',
'      await handleInvoicePaid({',
'        invoiceId: matched.id,',
'        reference,',
'        amount,',
'        channel,',
'        paid_at,',
'        isDva: true,',
'        business,',
'      });',
'    }',
'  }',
'',
'  return NextResponse.json({ ok: true });',
'}',
'',
'async function handleInvoicePaid({',
'  invoiceId,',
'  reference,',
'  amount,',
'  channel,',
'  paid_at,',
'  isDva = false,',
'  business: bizData,',
'}: {',
'  invoiceId: string;',
'  reference: string;',
'  amount: number;',
'  channel: string;',
'  paid_at: string;',
'  isDva?: boolean;',
'  business?: any;',
'}) {',
'  const { data: invoice } = await supabaseAdmin',
'    .from("invoices")',
'    .select("*")',
'    .eq("id", invoiceId)',
'    .single();',
'',
'  if (!invoice || invoice.status === "paid") return;',
'',
'  await supabaseAdmin',
'    .from("invoices")',
'    .update({ status: "paid", paid_at })',
'    .eq("id", invoiceId);',
'',
'  const receiptNumber = generateReceiptNumber(invoice.invoice_number);',
'  const { data: receipt } = await supabaseAdmin',
'    .from("receipts")',
'    .insert({',
'      invoice_id: invoiceId,',
'      user_id: invoice.user_id,',
'      receipt_number: receiptNumber,',
'      amount_paid: invoice.currency === "NGN" ? koboToNaira(amount) : amount / 100,',
'      payment_method: channel,',
'      paystack_reference: reference,',
'      paid_at,',
'    })',
'    .select()',
'    .single();',
'',
'  const { data: business } = bizData',
'    ? { data: bizData }',
'    : await supabaseAdmin.from("businesses").select("*").eq("user_id", invoice.user_id).single();',
'',
'  if (invoice.client_email && receipt) {',
'    await sendReceiptEmail(invoice, receipt, business).catch(console.error);',
'    await supabaseAdmin',
'      .from("receipts")',
'      .update({ emailed_at: new Date().toISOString() })',
'      .eq("id", receipt.id);',
'  }',
'',
'  // For DVA payments, automatically transfer 98% to business bank account',
'  if (isDva && business) {',
'    await transferToBusiness(business, amount);',
'  }',
'',
'  console.log("Invoice marked paid:", invoiceId);',
'}',
'',
'export const config = { api: { bodyParser: false } };',
].join('\n');

fs.writeFileSync('app/api/webhooks/paystack/route.ts', content, { encoding: 'utf8' });
console.log('Done');